version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "version-bump"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 30
